services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: todo_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7.0
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - MYSQL_HOST=db 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=todo_db
      - REDIS_URL=redis://redis:6379/0
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    depends_on:
    - backend
    - frontend

volumes:
  db_data: